QBShared = QBShared or {}
QBShared.Items = {
 
		--Custom Weapons ~Tables~
	--Custom Melee
	['weapon_steelmace'] 			= {['name'] = 'weapon_steelmace', 	 	  	 ['label'] = 'Medival War Mace', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,					['image'] = 'weapon_steelmace.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_penetrator'] 			= {['name'] = 'weapon_penetrator', 	 	  	 ['label'] = 'The Penetrator', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,					    ['image'] = 'weapon_penetrator.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_khukuri'] 				= {['name'] = 'weapon_khukuri', 	 	  	 ['label'] = 'Khukuri', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,					        ['image'] = 'weapon_khukuri.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_berserker'] 			= {['name'] = 'weapon_berserker', 	 	  	 ['label'] = 'Berserker', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,					        ['image'] = 'weapon_berserker.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_katana'] 			    = {['name'] = 'weapon_katana', 	 		  	['label'] = 'Katana', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'katana.png', 							['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A single-edged sword that is the longer of a pair worn by the Japanese samurai.'},
	['weapon_sledgehammer'] 		= {['name'] = 'weapon_sledgehammer', 	 		  	['label'] = 'Sledge Hammer', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = nil,		['image'] = 'sledgehammer.png', 							['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A Sledge Hammer to destroy peoples heads'},
    ['weapon_sword'] 		        = {['name'] = 'weapon_sword', 			    ['label'] = 'Sword', 		    ['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'nil',			  				['image'] = 'weapon_sword.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'A BIG SWORD BIGGER THAN YOUR PP'},
    ['weapon_riftedge'] 			= {['name'] = 'weapon_riftedge', 			['label'] = 'Riftedge', 		['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'nil',			   			    ['image'] = 'weapon_riftedge.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'VERY BIG THING TO CUT PEOPLE UP'},
	['weapon_krambit'] 			 	= {['name'] = 'weapon_krambit', 			['label'] = 'Krambit', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'nil',			   			    ['image'] = 'weapon_krambit.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'LMAO CSGO'},
    ['weapon_dildo'] 				= {['name'] = 'weapon_dildo', 			 	['label'] = 'Dildo', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'nil',						    ['image'] = 'weapon_dildo.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'YOU CAN GIVE THIS TO YOUR GIRLFRIEND'},
	['weapon_shiv'] 				= {['name'] = 'weapon_shiv', 			 	  	['label'] = 'Shiv', 					['weight'] = 3000, 		['type'] = 'weapon', 	['ammotype'] = nil,					['image'] = 'shiv.png', 							['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'An instrument composed of a blade fixed into a handle, used for cutting or as a weapon'},
	['weapon_keyboard'] 			= {['name'] = 'weapon_keyboard', 			['label'] = 'Keyboard', 		['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'nil',			    			['image'] = 'weapon_keyboard.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'YOU CAN USE THIS TO HIT YOUR SON xD'},
	['weapon_katana'] 				= {['name'] = 'weapon_katana', 		 	  	 ['label'] = 'Cursed Katana', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'np_cursed-katana.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'Infused with the blood of a Dragon; a normal human mind cannot control such power.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_shiv'] 				= {['name'] = 'weapon_shiv', 			 	 ['label'] = 'Prison Shiv', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'np_shiv.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'Prison Shiv', ['created'] = nil, ['decay'] = 14.0},
	['weapon_sledgeham'] 			= {['name'] = 'weapon_sledgeham', 			 ['label'] = 'Sledge Hammer', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'np_sledgehammer.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'Big and girthy.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_pick'] 			= {['name'] = 'weapon_pick', 			 ['label'] = 'Precision Pickaxe', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'weapon_pick.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'You might be able to use this to find rare gems!'},

	--Custom Pistols
	['weapon_glock22'] 			     = {['name'] = 'weapon_glock22', 			 	['label'] = 'Glock 22', 				['weight'] = 7000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',					['image'] = 'weapon_glock22.png', 						['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'pistol'},
	['weapon_python'] 							= {['name'] = 'weapon_python', 	 	  	 ['label'] = 'Colt Python', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,							['image'] = 'weapon_python.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_ragingbull'] 							= {['name'] = 'weapon_ragingbull', 	 	  	 ['label'] = 'Ragin Bull', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'weapon_ragingbull.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_glock17'] 				 = {['name'] = 'weapon_glock17', 			 	['label'] = 'PD Glock 17', 				['weight'] = 7000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',					['image'] = 'glock-17.png', 						['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'PD GUN'},
	['weapon_de'] 					 = {['name'] = 'weapon_de', 			 	  	['label'] = 'Desert Eagle',			    ['weight'] = 8000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',					['image'] = 'deagle.png', 							['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A .50 caliber firearm designed to be held with both hands'},
	['weapon_fnx45'] 				 = {['name'] = 'weapon_fnx45', 	 			  	['label'] = 'FN FNX-45', 				['weight'] = 7000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',					['image'] = 'weapon_combat-pistol.png', 			['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A combat version small firearm designed to be held in one hand'},
	['weapon_m9'] 					 = {['name'] = 'weapon_m9', 				 	['label'] = 'Beretta M9A3', 			['weight'] = 7000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',					['image'] = 'm1911.png', 							['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A M91'},
	['weapon_m1911'] 				 = {['name'] = 'weapon_m1911', 	 			  	['label'] = 'M1911', 					['weight'] = 7000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',					['image'] = 'browning.png',  						['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A hefty firearm designed to be held in one hand (or attempted)'},
 	['weapon_glock20'] 		     	 = {['name'] = 'weapon_glock20', 			['label'] = 'Glock-20', 		['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',								['image'] = 'weapon_glock20.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'Police Glock'},
 	['weapon_browning'] 				 = {['name'] = 'weapon_browning', 			 	['label'] = 'Browning Hi-Power', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',			['image'] = 'np_browning.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'Browning Pistol', ['created'] = nil, ['decay'] = 14.0},
	['weapon_manurhin'] 							= {['name'] = 'weapon_manurhin', 	 	  	 ['label'] = 'Manurhin', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'weapon_manurhin.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},
	['weapon_bdhg'] 							= {['name'] = 'weapon_bdhg', 	 	  	 ['label'] = 'Big Daddy`s Handgun', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = nil,						['image'] = 'weapon_bdhg.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'This was stolen from a british war museum.', ['created'] = nil, ['decay'] = 14.0},

	--Custom Submachine guns
	['weapon_aks74'] 		 		 = {['name'] = 'weapon_aks74', 	 			  	['label'] = 'AK-S74', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',			['image'] = 'weapon_aks74.png', 				    ['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},
	['weapon_uzi'] 					 = {['name'] = 'weapon_uzi', 			 	  	['label'] = 'UZI', 						['weight'] = 10000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_SMG',				['image'] = 'uzi.png', 								['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A handheld lightweight machine gun'},
	['weapon_mac10'] 				 = {['name'] = 'weapon_mac10', 			 	  	['label'] = 'MAC-10', 					['weight'] = 10000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_SMG',				['image'] = 'mac-10.png', 							['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A handheld lightweight machine gun'},
    ['weapon_mp9'] 				     = {['name'] = 'weapon_mp9', 			 	['label'] = 'Mp-9', 				['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SMG',						['image'] = 'weapon_mp9.png', 			['unique'] = true, 		['useable'] = false, 	['description'] = 'SMOKE EM'},
	['weapon_mp5'] 				     = {['name'] = 'weapon_mp5', 			 	['label'] = 'Mp-5', 				['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SMG',						['image'] = 'weapon_mp5.png', 			['unique'] = true, 		['useable'] = false, 	['description'] = 'A BETTER VERSION OF SMG'},

	--Custom Shotguns
	['weapon_mossberg'] 			 = {['name'] = 'weapon_mossberg', 			 	['label'] = 'Mossberg 500', 			['weight'] = 10000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_SHOTGUN',			['image'] = 'mossberg500.png',						['unique'] = true,	 	['useable'] = false,["created"] = nil,	['description'] = 'A sawn-off smoothbore gun for firing small shot at short range'},
	['weapon_remington'] 			 = {['name'] = 'weapon_remington', 		 	  	['label'] = 'Remington 870', 			['weight'] = 8000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SHOTGUN',			['image'] = 'remington.png', 						['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A pump-action smoothbore gun for firing small shot at short range'},
	['weapon_beanbag'] 			     = {['name'] = 'weapon_beanbag', 	 	  	['label'] = 'Beanbag', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SHOTGUN',						['image'] = 'weapon_beanbag.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'A shotgun? no!'},
	['weapon_spas12'] 			     = {['name'] = 'weapon_spas12', 	 	  	['label'] = 'Spas-12', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SHOTGUN',						['image'] = 'weapon_spas12.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'A shotgun? no!'},
	['weapon_komrad12'] 			     = {['name'] = 'weapon_komrad12', 	 	  	['label'] = 'Komrad-12', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SHOTGUN',						['image'] = 'weapon_komrad12.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'A shotgun? no!'},
	['weapon_saiga12g'] 			     = {['name'] = 'weapon_saiga12g', 	 	  	['label'] = 'Saiga-12G', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SHOTGUN',						['image'] = 'weapon_saiga12g.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'A shotgun? no!'},
	['weapon_aa12'] 			     = {['name'] = 'weapon_aa12', 	 	  	['label'] = 'AA-12', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SHOTGUN',						['image'] = 'weapon_aa12.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'A shotgun? no!'},

	--Custom Assault Rifles
	['weapon_ak74'] 		 		 = {['name'] = 'weapon_ak74', 	 			  	['label'] = 'AK-74', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',			['image'] = 'weapon_ak74.png', 				        ['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},
	['weapon_ak47'] 		 		 = {['name'] = 'weapon_ak47', 	 			  	['label'] = 'AK-47', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',			['image'] = 'weapon_assaultrifle.png', 				['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},
    ['weapon_m4a1'] 				 = {['name'] = 'weapon_m4a1', 			 	['label'] = 'M4A1', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_PISTOL',						['image'] = 'weapon_m4a1.png', 			['unique'] = true, 		['useable'] = false, 	['description'] = 'PISTOLLLLL'},
	['weapon_pdm4a1'] 					 = {['name'] = 'weapon_pdm4a1', 	 			  	['label'] = 'PD M4A1', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',			['image'] = 'weapon_carbinerifle.png',			 	['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A lightweight automatic rifle for the Police'},
	['weapon_scarh'] 				 = {['name'] = 'weapon_scarh', 				 	['label'] = 'PD SCAR-H', 				['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',			['image'] = 'scar.png',								['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'An extremely versatile assault rifle for any combat situation'},
	['weapon_ar15'] 				 = {['name'] = 'weapon_ar15', 	 	 		 	['label'] = 'PD AR-15', 				['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',			['image'] = 'weapon_mcx.png', 						['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A lightweight automatic rifle for the Police'},
	['weapon_hk416'] 		         = {['name'] = 'weapon_hk416', 	 	  	['label'] = 'HK-416', 			['weight'] = 13000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',						['image'] = 'weapon_carbinerifle.png', 	['unique'] = true, 		['useable'] = false,["created"] = nil,["decay"] = 30.0,     	['description'] = 'A lightweight automatic rifle'},
	['weapon_famas'] 	 			 = {['name'] = 'weapon_famas', 	 				['label'] = 'Famas', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',					['image'] = 'weapon_famas.png', ['unique'] = true, 	['useable'] = true, 	['description'] = 'M4 Carbine Rifle', ['created'] = nil, ['decay'] = 14.0},
	['weapon_tar21'] 	 			 = {['name'] = 'weapon_tar21', 	 				['label'] = 'Tar 21', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',					['image'] = 'weapon_tar21.png', ['unique'] = true, 	['useable'] = true, 	['description'] = 'M4 Carbine Rifle', ['created'] = nil, ['decay'] = 14.0},
	['weapon_ar16'] 	 			 = {['name'] = 'weapon_ar16', 	 				['label'] = 'AR-16', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',					['image'] = 'weapon_ar16.png', ['unique'] = true, 	['useable'] = true, 	['description'] = 'M4 Carbine Rifle', ['created'] = nil, ['decay'] = 14.0},
	['weapon_fnfal'] 	 			 = {['name'] = 'weapon_fnfal', 	 				['label'] = 'FN-Fal', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',					['image'] = 'weapon_fnfal.png', ['unique'] = true, 	['useable'] = true, 	['description'] = 'M4 Carbine Rifle', ['created'] = nil, ['decay'] = 14.0},

	--Custom light machine guns
	['weapon_pkm'] 		 		 = {['name'] = 'weapon_pkm', 	 			  	['label'] = 'PKM', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',					['image'] = 'weapon_pkm.png', 				    ['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},
	['weapon_m249'] 		 	 = {['name'] = 'weapon_m249', 	 			  	['label'] = 'M249', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',		    	['image'] = 'weapon_m249.png', 				    ['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},
	['weapon_rpd'] 		 		 = {['name'] = 'weapon_rpd', 	 			  	['label'] = 'RPD', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',					['image'] = 'weapon_rpd.png', 				    ['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},
	['weapon_m249_mk2'] 		 	 = {['name'] = 'weapon_m249_mk2', 	 			  	['label'] = 'M249 Mk.2', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',		    	['image'] = 'weapon_m249.png', 				    ['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},
	['weapon_rpd2'] 		 		 = {['name'] = 'weapon_rpd2', 	 			  	['label'] = 'RPD Mk.2', 					['weight'] = 13000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',					['image'] = 'weapon_rpd.png', 				    ['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'},

	--Custom Sniper Rifles
	['weapon_m110'] 		         = {['name'] = 'weapon_m110', 	 	  	['label'] = 'M110', 			['weight'] = 23000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_SNIPER',						['image'] = 'weapon_m110.png', 	['unique'] = true, 		['useable'] = false,["created"] = nil,["decay"] = 30.0,     	['description'] = 'A very accurate single-fire rifle'},
 	['weapon_draco'] 				 = {['name'] = 'weapon_draco', 			 	['label'] = 'Draco', 			['weight'] = 1000, 		['type'] = 'weapon', 	['ammotype'] = 'AMMO_RIFLE',						['image'] = 'weapon_draco.png', 		['unique'] = true, 		['useable'] = false, 	['description'] = 'A SMALL ASSAULT RIFLE LIKE YOUR PP'},
	['weapon_mk14'] 				 = {['name'] = 'weapon_mk14', 	 			  	['label'] = 'PD MK14', 					['weight'] = 23000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_SNIPER',			['image'] = 'mk14.png', 							['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A very accurate single-fire rifle'},
	['weapon_huntingrifle'] 		 = {['name'] = 'weapon_huntingrifle', 	 	  	['label'] = 'Hunting Rifle', 			['weight'] = 23000, 	['type'] = 'weapon', 	['ammotype'] = 'AMMO_SNIPER',			['image'] = 'huntingrifle.png', 					['unique'] = true, 		['useable'] = false,["created"] = nil,	['description'] = 'A very accurate Rifle for hunting'},

}
